### ISSUE TITLE
Missing aeolus_top5drugs.feather

### ISSUE THREAD

**Issue by hsiaoyi0504** [NCBI-Hackathons/SafeDrugs#13]
When I want to start the web server by `python app.py`. It reports that there is no file `aeolus_top5drugs.feather`. I tried to find it in the repo or generate by scripts contained in jupyter notebooks, but it looks like that the file wasn't generated from there.

**Comment by ngiangre** [comment]
That’s because I have to share it with you – it’s too big (200 Mbs) to put on github. If you give me a gmail I can share a drive link with you

 

Cheers,

Nick

**Comment by hsiaoyi0504** [comment]
Thanks, my email is hsiaoyi0504@gmail.com. It will be good to share the link to the public, though.

**Comment by hsiaoyi0504** [comment]
@ngiangre Now it available at https://quiltdata.com/package/hsiaoyi0504/aeolus_top5drugs.

**Comment by ngiangre** [comment]
This is really cool! Do you want to implement the code accessing the data via quilt in the notebooks/app?

 

Cheers,

Nick

**Comment by hsiaoyi0504** [comment]
I will do that !

**Comment by ngiangre** [comment]
Thanks for contributing!

 

Cheers,

Nick

**Comment by ngiangre** [comment]
closing because we're now loading the data with quilt
